# Generated by Django 4.1.3 on 2024-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group1', '0002_category_exam_difficulty_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(upload_to='group1/audio_files/'),
        ),
    ]
